POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q4OEBleGFtcGxlLmNvbSIsImV4cCI6MTc0Mzk1NTIwNiwidXNlcklkIjoxfQ.hIqk-eli68-UU7HyqqD3gsrEbAFoIGLCXlpT8sHrKyk

{
    "name": "Event created by 88",
    "description": "Event created by 88",
    "location": "Event created by 88",
    "dateTime": "2025-01-01T15:30:00.000Z"
}

