DELETE http://localhost:8080/events/11
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Q4OEBleGFtcGxlLmNvbSIsImV4cCI6MTc0MzkyMzg5NywidXNlcklkIjo3fQ.p9fWwHyFHfRSv0gwc9Dx4ox9E69iwDggMSvqXL0CaZE

